server.port = 8080
spring.output.ansi.enabled=ALWAYS

# Config database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.username=postgres
spring.datasource.password=15963

# Config Hibernate - PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Config hikari connection pools
spring.datasource.hikari.maximum-pool-size=5

# Show queries SQL
spring.jpa.show-sql=true

# Hibernate mode
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create

